### ISSUE TITLE
是不是对sea.config.js中的alias 不支持

### ISSUE THREAD

**Issue by ckrad** [fouber/spmx#11]

**Comment by fouber** [comment]
@ckrad 

这个项目不是很可靠，没有支持最新的seajs

**Comment by ckrad** [comment]
那怎么破 我向使用fis来给资源做md5 现在全站都在使用seajs 没有现成的解决方案吗

**Comment by fouber** [comment]
@ckrad 

对seajs的改造成本可能会有点大，推荐用scrat吧，http://scrat-team.github.io/

**Comment by ckrad** [comment]
@fouber 
现在项目里还用了seajs-combo 用来做js线上动态合并 现在觉得线上动态合并比较灵活 最好还是用seajs

**Comment by ckrad** [comment]
还有我不太明白fis编译之前__url这个函数在js中怎么处理 照道理 我没有这个函数 那不是要全局写一个__url让代码正常执行

**Comment by ckrad** [comment]
我刚才看了一下fis扩展插件的机制 里面说单文件编译中standard是不可扩展的 我希望写一个插件让fis可以识别seajs.use(path)里面的路径 这个做到吗

**Comment by fouber** [comment]
@ckrad 

你并不需要这样做。fis构建之后，会产生一个map.json的文件结构，用于记录所有的资源依赖关系。你只需要扩展fis的postpackager插件，把这个数据结构改造一下，插入到页面上。比如你的html这么写：

```html
...
<script>
sea.config({
    res: __FRAMEWORK_CONF__
});
</script>
...
```

这个 ``__FRAMEWORK_CONF__`` 是自定义的，然后写一个 ``postpackager`` 插件，把fis收集到的map.json结构替换掉这个变量，比如：

```js
fis.config.set('modules.postpackager', function(ret){
    var map = JSON.stringify(ret.map.res); // 把fis收集的map结构序列化
    fis.util.map(ret.src, function(path, file){
        if(file.isHtmlLike || file.isJsLike){    // 对html或者js文件进行批评
            var content = file.getContent();  // 获取内容
            content = content.replace(/__FRAMEWORK_CONF__/g, map);  //替换占位符
            file.setContent(content);   //重置文件内容
        }
    });
});
```

这样，前面的html，经过构建之后就变成了：

```html
...
<script>
  sea.config({
      res: {
        "components/boot/boot.css": {
          "uri": "/components/boot/boot_4bb6b98.css",
          "type": "css"
        },
        "components/boot/boot.js": {
          "uri": "/components/boot/boot_d5ba2f1.js",
          "type": "js",
          "deps": [
            "components/boot/boot.css"
          ]
        },
        "views/index.css": {
          "uri": "/views/index_9c4b360.css",
          "type": "css"
        },
        "views/lib/normalize.css": {
          "uri": "/views/lib/normalize_4ca5372.css",
          "type": "css"
        },
        "views/lib/scrat.js": {
          "uri": "/views/lib/scrat_b7bc9ca.js",
          "type": "js"
        }
      }
  });
</script>
...
```

资源id、带md5戳的url、依赖关系等等信息都已经写入到页面上了。

好了，接下来，我们写一个seajs的插件，监听路径处理时候的事件，无论是sea.use，还是require接口，当要加载一个资源的时候，就先查一下资源表，找到真正的url路径，再去加载。

这就是fis的资源管理与模块化框架结合的方法。

**Comment by ckrad** [comment]
@fouber 
我前面提的seajs.use的问题是我搞错了 我昨天测试了一下 是可以用__uri替换的 fis我现在只想在上线前用它做资源定位 开发的时候不想用到fis 昨天遇到一个问题 在seajs中定义模块 id一般是用模块的文件路径 __uri不能定位自身所在的文件 
unable to embed file[/Users/c/playground/fis/index.js] into itself. in [/index.js] in [/index.html]
我现在想到的是 先用fis做资源定位 然后用脚本根据所在文件名去替换id 您说的方法应该解决不了这个问题 不知道还有没有更好的方式 处理这个问题

**Comment by ckrad** [comment]
@fouber 
貌似您说的方式是可以解决id这个问题 我不需要替换它 但是在线下开发的时候 不使用fis 程序不是没办法执行了 这个怎么处理

**Comment by fouber** [comment]
@ckrad 

相信我，web前端是必须经过构建才能运行的程序，这是它的本质。``线下开发不构建``是不合理的预期，因为运行时会有不一致的问题。正确的思路是线下线上用相同的手段进行构建，然后降低线下调试的成本，比如fis采用watch+livereload的方式，监听文件变化并自动刷新，使得线下开发的便捷程度跟直接的文件访问一样，甚至比直接访问还方便，因为摆在那里就能自动刷新：

![show](https://cloud.githubusercontent.com/assets/536297/6314651/36874b8e-ba22-11e4-8051-50c57df6c898.gif)

**Comment by fouber** [comment]
@ckrad 

上面动画截图展示的是fis线下开发调试的工作过程：

1. fis server start，启动内置浏览器
2. fis release -wL，对项目进行文件监听和自动刷新
3. 把编辑器和浏览器摆在一起，然后保存代码浏览器就自动刷新，也能实时看到代码执行的效果

本地的构建和线上构建保持一致，使得线下开发的效果可以放心的部署到线上，再加上自动刷新，我不相信没有达到甚至超过你的理想预期

**Comment by ckrad** [comment]
@fouber 我们站现在用的是gulp 开始使用fis最大的原因是因为md5戳 fis可以完成很多我现在在gulp里完成的功能 本来有想过要统一都是用fis 但是一个觉得人力有限（现在前端只有我一个）第二个是觉得gulp更灵活一点 livereload我用过一段时间 对实际开发提高生产力不是特别明显 我对fis最大的期望是能够帮我实现模块化 现在最大的问题是我们站使用的是thinkphp的模板

**Comment by fouber** [comment]
@ckrad 

实现模块化是一个比较麻烦的事
